defaults: &defaults
    working_directory: /angular-bro-app
    docker:
        - image: adambullmer/circleci-node:6.10.3

version: 2
jobs:

    test:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: npm-config
                command: 'npm config set progress=false'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install-npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: .
                paths:
                    - node_modules
            - run:
                name: unit-tests
                command: npm run test -- --reporter mocha-junit-reporter --reporter-options mochaFile=$(pwd)/junit/test-results.xml
            - run:
                name: collect-coverage
                command: npm run coverage -- --report-dir coverage/
            # - run:
            #     name: report-coveralls-coverage
            #     command: npm run coveralls
            - store_test_results:
                path: /angular-bro-app/junit
            - store_artifacts:
                path: coverage
                prefix: coverage

    deploy:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: prep-node-credentials
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run:
                name: publish-npm
                command: npm publish

workflows:
    version: 2
    build_and_test:
        jobs:
            - test:
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: master
